ui/src/assets/icons/close.svg
ui/src/components/atoms/Drawer/Drawer.tsx
ui/src/components/atoms/Drawer/index.ts
ui/src/components/icons/CloseIcon.tsx

feat: implement common drawer

---

wasm-app/src/components/modules/CollapsibleTable.tsx
wasm-app/src/components/pages/home/WorkloadList.tsx
wasm-app/src/components/pages/home/workload-detail/ClosePort.tsx
wasm-app/src/components/pages/home/workload-detail/OpenPort.tsx
wasm-app/src/components/pages/home/workload-detail/PortDetail.tsx
wasm-app/src/components/pages/home/workload-detail/WorkloadSummary.tsx
wasm-app/src/models/index.ts

fix: fix lint

---

wasm-app/src/components/atoms/Drawer.tsx
wasm-app/src/components/modules/CollapsibleTable.tsx
wasm-app/src/components/pages/home/WorkloadDetail.tsx
wasm-app/src/components/pages/home/workload-detail/ClosePort.tsx
wasm-app/src/components/pages/home/workload-detail/OpenPort.tsx
wasm-app/src/components/pages/home/workload-detail/WorkloadTabs.tsx

fix: fix css workload detail

---

wasm-app/src/App.tsx
wasm-app/src/components/modules/networkgraph/edge.ts
wasm-app/src/components/modules/networkgraph/networkGraph.tsx
wasm-app/src/components/modules/networkgraph/node.ts
wasm-app/src/components/modules/networkgraph/types.ts
wasm-app/src/components/pages/home/WorkloadMap.tsx
wasm-app/src/wasm.provider.tsx

feat: update workload map

---

wasm-app/src/components/modules/SelectClusterAndNameSpace.tsx

fix: fix select

---

wasm-app/src/components/modules/BadgePortStatus.tsx
wasm-app/src/components/pages/home/WorkloadDetail.tsx
wasm-app/src/components/pages/home/workload-detail/ClosePort.tsx
wasm-app/src/components/pages/home/workload-detail/OpenPort.tsx
wasm-app/src/components/pages/home/workload-detail/PolicyApplication.tsx
wasm-app/src/components/pages/home/workload-detail/WorkloadSummary.tsx
wasm-app/src/components/pages/home/workload-detail/WorkloadTabs.tsx
wasm-app/src/components/pages/home/workload-detail/data.ts
wasm-app/src/constants/index.ts
wasm-app/src/models/index.ts
wasm-app/src/utils/format.ts
wasm-app/src/utils/index.ts

feat: handle logic workload detail

---

wasm-app/src/components/atoms/Datagrid.tsx
wasm-app/src/components/pages/home/WorkloadList.tsx

revert: logic worklist

---

wasm-app/src/components/atoms/Drawer.tsx
wasm-app/src/components/icons/DownIcon.tsx
wasm-app/src/components/modules/CollapsibleTable.tsx
wasm-app/src/components/modules/SelectClusterAndNameSpace.tsx
wasm-app/src/components/pages/home/WorkloadDetail.tsx
wasm-app/src/components/pages/home/workload-detail/ClosePort.tsx
wasm-app/src/components/pages/home/workload-detail/OpenPort.tsx
wasm-app/src/components/pages/home/workload-detail/PolicyApplication.tsx
wasm-app/src/components/pages/home/workload-detail/WorkloadSummary.tsx
wasm-app/src/components/pages/home/workload-detail/_PortSettingModal.tsx
wasm-app/src/models/index.ts
wasm-app/src/utils/index.ts

fix: fix css feedback

---

wasm-app/src/components/atoms/Datagrid.tsx
wasm-app/src/components/modules/SearchComplete.tsx
wasm-app/src/components/modules/SelectClusterAndNameSpace.tsx
wasm-app/src/components/pages/home/WorkloadList.tsx

fix commin worklist

---

wasm-app/src/data/index.ts

fix: update dummy data

---

wasm-app/src/components/atoms/DescriptionWithDetails.tsx
wasm-app/src/components/pages/home/workload-detail/ClosePort.tsx
wasm-app/src/components/pages/home/workload-detail/OpenPort.tsx

fix: fix bug css feedback

---

wasm-app/src/components/modules/TabsViewMode.tsx

change color tab

---

wasm-app/src/components/atoms/Datagrid.tsx

fix table shake

---

wasm-app/src/components/atoms/ModalFooter.tsx
wasm-app/src/components/modules/ModalClosePort.tsx
wasm-app/src/components/pages/home/WorkloadList.tsx

fix: fix bug modal common

---

wasm-app/src/components/pages/home/WorkloadDetail.tsx
wasm-app/src/constants/index.ts
wasm-app/src/models/index.ts
wasm-app/src/services/getworkloadDetail.ts

feat: apply wasm workload detail

---

wasm-app/src/components/pages/home/WorkloadDetail.tsx
wasm-app/src/components/pages/home/WorkloadMap.tsx
wasm-app/src/components/pages/home/workload-detail/PolicyApplication.tsx
wasm-app/src/components/pages/home/workload-detail/PortDetail.tsx
wasm-app/src/components/pages/home/workload-detail/_PortSettingModal.tsx
wasm-app/src/pages/Home.tsx
wasm-app/src/store/index.ts

fix: fix bug jira and logic view detail

---

wasm-app/package.json
wasm-app/src/components/pages/home/WorkloadDetail.tsx
wasm-app/src/components/pages/home/workload-detail/OpenPort.tsx
wasm-app/src/components/pages/home/workload-detail/PortDetail.tsx
wasm-app/src/models/index.ts
wasm-app/src/utils/format.ts

update mapping workload detail

---

wasm-app/src/components/pages/home/workload-detail/ClosePort.tsx
wasm-app/src/components/pages/home/workload-detail/PortDetail.tsx
wasm-app/src/models/index.ts
wasm-app/src/utils/format.ts
wasm-app/src/utils/index.ts

fix: fix bug selftest

---

wasm-app/src/components/modules/networkgraph/constants.ts
wasm-app/src/components/modules/networkgraph/edge.ts
wasm-app/src/components/modules/networkgraph/imageLoader.ts
wasm-app/src/components/modules/networkgraph/networkGraph.tsx
wasm-app/src/components/modules/networkgraph/node.ts
wasm-app/src/components/modules/networkgraph/types.ts
wasm-app/src/components/pages/home/WorkloadMap.tsx
wasm-app/src/models/index.ts
wasm-app/src/services/listWorkloads.ts

[WIP] Rs/feat/duongnt1/update workload map

---

wasm-app/src/components/modules/workload-detail/ClosePort.tsx
wasm-app/src/components/modules/workload-detail/OpenPort.tsx
wasm-app/src/components/modules/workload-detail/PolicyApplication.tsx
wasm-app/src/components/modules/workload-detail/WorkloadDetail.tsx
wasm-app/src/models/index.ts
wasm-app/src/services/closeNotActivePorts.ts
wasm-app/src/utils/index.ts

feat: apply wasm service policies modal
